### ISSUE TITLE
Reimplement this in terms of upstream `Homebrew::Attestation`

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/homebrew-brew-verify#8]
Blocked on a merger of https://github.com/Homebrew/brew/pull/17049.

**Comment by woodruffw** [comment]
https://github.com/Homebrew/brew/pull/17049 is merged, so unblocked here.

**Comment by woodruffw** [comment]
Done.

**Comment by Abdullah9990** [comment]
@copllot
